# файл для локального запуска проекта в докере

version: "3"

services:
  front:
    image: registry.gitlab.com/ashugaev/sounds/front:v1
    restart: always
    build:
      context: .
      dockerfile: front/Dockerfile
    expose:
      - 8082
    ports:
      - "8005:8082"

  server:
    image: registry.gitlab.com/ashugaev/sounds/server:v1
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    expose:
      - 3000
    ports:
      # наружний порт:внутренний
      - "3005:3000"

  parser:
    image: registry.gitlab.com/ashugaev/sounds/parser:v1
    restart: always
    build:
      context: .
      dockerfile: parser/Dockerfile
    volumes:
      - "./parser/logs:/app/logs"