apiVersion: apps/v1
kind: Deployment
metadata:
  name: sounds-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sounds-back
  template:
    metadata:
      labels:
        app: sounds-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: sounds-back
          image: registry.gitlab.com/ashugaev/sounds/server:v1
          ports:
            - containerPort: 3005
              name: sounds
---
apiVersion: v1
kind: Service
metadata:
  name: sounds-back
spec:
  ports:
    - port: 3000
  selector:
    app: sounds-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sounds-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sounds-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sounds-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: sounds-front
          image: registry.gitlab.com/ashugaev/sounds/front:v1
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: REDIS
              value: "sounds-back"
---
apiVersion: v1
kind: Service
metadata:
  name: sounds-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: sounds-front
